### ISSUE TITLE
REPORT_STATUS message IDs are non-zero

### ISSUE THREAD

**Issue by w-figtree-neura** [w-figtree-neura/StableEyesV4#3]
The device firmware (421) currently generates an incrementing message ID for REPORT_STATUS messages when they should be 0.

This breaks message matching on the PC side which expects messages to only have an ID if they are sent in response to a message sent to the device. The following log illustrates the issue:

NEW MESSAGE 5 of type SET_LED_BRIGHTNESS
GOT MESSAGE 1 of type REPORT_STATUS
GOT MESSAGE 2 of type REPORT_STATUS
GOT MESSAGE 3 of type REPORT_STATUS
GOT MESSAGE 4 of type REPORT_STATUS
GOT MESSAGE 5 of type REPORT_STATUS
GOT MESSAGE 6 of type REPORT_STATUS
GOT MESSAGE 5 of type SET_LED_BRIGHTNESS

A workaround is currently in place c90481ae7c06ef472c56eeeeebdbc88e774cf8cd to ignore REPORT_STATUS message IDs but they really shouldn't be being generated in the first place. Without the workaround, an exception is thrown when the 5th REPORT_STATUS message is received since it cannot convert the contents to a SET_LED_BRIGHTNESS message.

**Comment by w-figtree-neura** [comment]
Whoops this is the old repo. Copied this issue to the new repo.

**Comment by c-todd** [comment]
I'm not a member of the new repo. Can you add me?

**Comment by w-figtree-neura** [comment]
Hi, 

I'll add you in a bit. Bitbucket is having some user profile issues at the moment so I'll wait for them to sort that out first.
